# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 83ccc144447a0f3e9c3881a163c7ed261846860ce6a29aa5bd7be7ef80e7255bee354d09fb5cd5da4389c5d43e8a7a2ace3d439a89eeb6e4bea51c5a4711f38b

test:
  secret_key_base: 98bc7017add39e2096cca273bb3d1c1e93abc3cba6d2b14c4842464937ac86d31741b95be888b42259ce03f31b2fd57c3797730f53e5082b9c71b01d29b91e1b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
