# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e99b38054718e30f6f98685c4c737b2a1194fd2f854b74e3a7be26c5a4b82ed8a910601bcdf12c7b6b497949358564d854a35499b1807341c02dfa5c9eff653

test:
  secret_key_base: c453d466c442c15223fdd926e2459b990098f435e34189c52ace6b0e9691549de57a8a67a4b06f7f4ac651008cef0e42436c8da0c621f7fbc158ecb8fb49b885

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
