# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 90edcd44d94c197a57c28da3666fc679e02e9d6ae4b879aaf03ff1c485dda74e5dd9f3015a992a1a08b294eed8277d11655e8d58e5b1040c06a22f48e8f2b28a

test:
  secret_key_base: c8f158cb27b2e94c814d79d370ea5fca311201dce4b36d765413f590b644f054b0ad6694612ce20c24e4bca504c9c7d305e0f3c9858c8dbaeeda3e91073eb3d0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
